env: "local"
storage_path: "./storage/storage.db"
app_name: "url-shortener"
http_server:
  address: "localhost:8085"
  read_timeout: 4s
  write_timeout: 5s
  idle_timeout: 60s
  aliasLength: 6
clients:
  sso:
    address: "localhost:8088"
    timeout: "5s"
    retries_count: 5