env: "local"
storage_path: "./storage/storage.db"
app_secret: "asdfghjkl;"
http_server:
  address: "localhost:8085"
  read_timeout: 4s
  write_timeout: 5s
  idle_timeout: 60s
  user: "admin"
  password: "123"
  aliasLength: 6
clients:
  sso:
    address: "localhost:8088"
    timeout: "5s"
    retries_count: 5